"""Central configuration.

All runtime configuration is sourced from environment variables (with sane
local-dev defaults) via pydantic-settings, following 12-factor conventions.
Never hardcode secrets — see .env.example for the full variable list.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

# `src/nids/config.py`'s own directory *is* the installed `nids` package —
# true whether it's an editable install (`src/nids/`, repo layout intact)
# or a real wheel install (`site-packages/nids/`, no "src" or repo root at
# all). rules/definitions/*.yaml genuinely ships *inside* the package, so
# it must be resolved this way, not via a fragile "walk up N parents to
# find the project root" guess — that guess silently breaks (0 rules
# loaded, no error) the moment this runs from a built wheel instead of an
# editable install, e.g. exactly the Dockerfile's install path.
_PACKAGE_DIR = Path(__file__).resolve().parent


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_prefix="NIDS_",
        case_sensitive=False,
        extra="ignore",
    )

    # --- App metadata ---
    app_name: str = "nids"
    environment: str = Field(default="development")  # development | staging | production
    log_level: str = Field(default="INFO")
    log_json: bool = Field(default=False)

    # --- API ---
    api_host: str = Field(default="0.0.0.0")
    api_port: int = Field(default=8000)
    api_cors_origins: list[str] = Field(default_factory=lambda: ["http://localhost:5173"])
    api_key: str | None = Field(default=None, description="Static API key for write endpoints")

    # --- Database ---
    database_url: str = Field(
        default="postgresql+asyncpg://nids:nids@localhost:5432/nids",
        description="SQLAlchemy async DSN for the alert/flow store",
    )
    database_echo: bool = Field(default=False)

    # --- Capture ---
    capture_interface: str | None = Field(
        default=None, description="NIC to sniff, e.g. eth0 / Wi-Fi. None = replay-only mode."
    )
    capture_bpf_filter: str = Field(default="ip or ip6")
    flow_idle_timeout_s: float = Field(default=15.0)
    flow_active_timeout_s: float = Field(default=120.0)

    # --- Detection ---
    rules_dir: Path = Field(default=_PACKAGE_DIR / "rules" / "definitions")
    # models/ is never bundled *inside* the package (it's generated by
    # `nids train`, gitignored, mounted as a volume in Docker) — so unlike
    # rules_dir there's no "package data" location to anchor to. This
    # default is CWD-relative, matching every documented workflow (run
    # `nids ...` from the repo root); any deployment where that's not
    # true already sets NIDS_ML_MODEL_PATH explicitly (see
    # docker-compose.yml's api service).
    ml_model_path: Path = Field(default=Path("models/anomaly_model.joblib"))
    ml_anomaly_threshold: float = Field(default=0.5, ge=0.0, le=1.0)
    ml_enabled: bool = Field(default=True)

    # --- Alerting ---
    alert_webhook_url: str | None = Field(default=None)
    alert_min_severity: str = Field(default="low")  # low | medium | high | critical

    @property
    def is_production(self) -> bool:
        return self.environment.lower() == "production"

    @property
    def database_url_masked(self) -> str:
        """`database_url` with any password redacted — log/print this,
        never the raw field. A real credential-leak risk otherwise: the
        DSN embeds the DB password inline (`postgresql+asyncpg://user:pass@host/db`),
        and this app used to log it verbatim on a startup-warning path —
        exactly the kind of thing that ends up copy-pasted into a log
        aggregator or an issue tracker.
        """
        parts = urlsplit(self.database_url)
        if parts.password is None:
            return self.database_url
        userinfo = parts.username or ""
        if parts.username:
            userinfo += ":***"
        netloc = f"{userinfo}@{parts.hostname or ''}"
        if parts.port:
            netloc += f":{parts.port}"
        return urlunsplit((parts.scheme, netloc, parts.path, parts.query, parts.fragment))


@lru_cache
def get_settings() -> Settings:
    """Cached settings singleton — import this, not Settings() directly."""
    return Settings()
